"""India-access pass A859 regression tests: the per-lot DATA cost is measured,
gated under 2 MB per session, and the service worker that zeroes repeat-visit
shell cost is pinned down.

Why this matters: .agent/IMPACT_EVIDENCE.md §4b is generated by
scripts/impact_evidence.py from files in this repo. Loop A859 used it to
catch a real violation -- at the old 1280 px/q82 annotated JPEG a full
±6-pt sufficiency sample (6 looks) measured 2.61 MB over the wire, over the
<2 MB session budget. The annotated constants moved to 960 px/q76
(annotated_scale derives from them, so client tap mapping stays consistent)
and replays were rebuilt: median downlink fell 276 KB -> ~143 KB per look.

These tests pin three things:
  1. the measurement arithmetic and its budget gate (real numbers, not
     static text);
  2. the annotated-constant fix, so nobody silently re-inflates the
     downlink;
  3. the service worker's blast radius -- same-origin GETs under /static/
     and /api/replay/N ONLY, registered guarded in index.html, vanilla JS,
     node-parseable -- plus a zero-external-subresource guard that protects
     both the offline judge demo and the data-budget claim.

Run:
    C:/Users/ADMIN/AppData/Local/Programs/Python/Python311/python.exe -m pytest tests/test_data_cost.py -q
"""

from __future__ import annotations

import importlib.util
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "app" / "static"
SESSION_BUDGET_KB = 2048


@pytest.fixture(scope="module")
def ie():
    """The impact_evidence module, imported straight from scripts/."""
    spec = importlib.util.spec_from_file_location(
        "impact_evidence", ROOT / "scripts" / "impact_evidence.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------
# 1. The measured numbers and their gate
# --------------------------------------------------------------------------


def test_uplink_is_measured_from_real_repo_photos(ie):
    dc = ie.data_cost()
    assert dc["n_photos"] >= 10, "uplink sample suspiciously small"
    assert dc["up_min_kb"] > 0 and dc["up_max_kb"] >= dc["up_median_kb"]
    # The client clamp must be mirrored from index.html's own constants...
    assert dc["upload_max_edge"] == 1600
    assert dc["jpeg_quality"] == 80


def test_downlink_measured_and_shrunk_by_a859(ie):
    dc = ie.data_cost()
    assert dc["n_replays"] == 6, "judge demo expects six cached replays"
    # A859 halved this from 276 KB; if it creeps back over ~200 KB the
    # sufficiency-sample session line below starts failing for real.
    assert dc["down_median_kb"] <= 200, (
        f"per-look downlink regressed to {dc['down_median_kb']} KB")


def test_every_modelled_session_stays_under_the_2mb_budget(ie):
    dc = ie.data_cost()
    sessions = [
        ("first visit, 2 looks", ie.session_cost_kb(dc, 2, first_visit=True)),
        ("repeat visit, 2 looks", ie.session_cost_kb(dc, 2, first_visit=False)),
        ("repeat visit, 6 looks", ie.session_cost_kb(dc, 6, first_visit=False)),
    ]
    for label, kb in sessions:
        assert kb <= SESSION_BUDGET_KB, (
            f"{label} costs {kb:.0f} KB — over the {SESSION_BUDGET_KB} KB "
            "session budget; shrink ANNOTATED_* or the shell before shipping")


def test_generated_markdown_states_data_cost_honestly(ie):
    md = ie.build_markdown(ie.groundtruth_stats(), {})
    section = md.split("## 4b")[1].split("## 5")[0]
    assert "Data cost per grading session" in section
    assert "MEASURED-IN-REPO" in section, "measured figures must say so"
    assert "ASSUMED" in section, "assumed figures must be labelled"
    assert "PASS" in section, "budget verdict must be printed"
    assert "₹" in section, "the rupee story must be in rupees"
    assert "does NOT eliminate physical sorting" in section, (
        "the manual-comparison frame must stay narrow and honest")
    assert re.search(r"≈₹\d+\.\d\d of data", section)


# --------------------------------------------------------------------------
# 2. The downlink fix itself: annotated JPEG constants
# --------------------------------------------------------------------------


def test_annotated_constants_keep_downlink_small():
    src = (ROOT / "app" / "main.py").read_text(encoding="utf-8")
    m_w = re.search(r"ANNOTATED_MAX_WIDTH\s*=\s*(\d+)", src)
    m_q = re.search(r"ANNOTATED_JPEG_QUALITY\s*=\s*(\d+)", src)
    assert m_w and m_q, "annotated constants missing"
    width, quality = int(m_w.group(1)), int(m_q.group(1))
    assert (width, quality) == (960, 76), (
        f"annotated payload constants moved to {width}px/q{quality}; "
        "re-run scripts/build_replay.py and re-check IMPACT_EVIDENCE §4b "
        "against the 2 MB session budget before committing")
    # annotated_scale must derive from the constant, not a second literal.
    assert "ANNOTATED_MAX_WIDTH / image.shape[1]" in src


# --------------------------------------------------------------------------
# 3. The service worker: tiny blast radius, parseable, registered guarded
# --------------------------------------------------------------------------

SW = (STATIC / "sw.js").read_text(encoding="utf-8") \
    if (STATIC / "sw.js").exists() else ""


def test_sw_exists_and_is_vanilla_js():
    assert SW, "app/static/sw.js missing"
    assert "import " not in SW.replace("self.importScripts", ""), \
        "no ES modules in the worker"
    assert "require(" not in SW, "no CommonJS either"
    assert re.search(r"CACHE_VERSION\s*=\s*'sama-", SW), "cache version missing"


def test_sw_never_touches_non_get_or_cross_origin_or_other_paths():
    assert "req.method !== 'GET'" in SW, "must ignore non-GET"
    assert "url.origin === self.location.origin" in SW, "must be same-origin only"
    assert "url.pathname.startsWith('/static/')" in SW
    assert re.search(r"\^\\/api\\/replay\\/\\d\+\$", SW), \
        "replay allowlist regex missing"
    # Exactly two respondWith calls, one per allowlisted family.
    assert SW.count("respondWith") == 2


def test_sw_is_parseable_javascript():
    node = shutil.which("node")
    if not node:
        pytest.skip("node not installed on this machine")
    r = subprocess.run([node, "--check", str(STATIC / "sw.js")],
                       capture_output=True, text=True)
    assert r.returncode == 0, f"sw.js syntax error:\n{r.stderr}"


def test_index_registers_worker_only_where_safe():
    idx = (STATIC / "index.html").read_text(encoding="utf-8")
    assert "'serviceWorker' in navigator" in idx
    assert "location.protocol === 'https:'" in idx, \
        "plain-HTTP LAN testing must skip registration"
    assert "location.hostname === 'localhost'" in idx
    assert ".catch(() => {})" in idx, "registration failure must be silent"


# --------------------------------------------------------------------------
# 4. Zero external subresources: protects the offline demo AND the budget
# --------------------------------------------------------------------------


ALLOWED_EXTERNAL_HREF_PREFIXES = (
    # User-initiated WhatsApp share NAVIGATION, not a loaded subresource;
    # nothing downloads unless the officer taps it.
    "https://wa.me/?text=",
)


@pytest.mark.parametrize("page", sorted(p.name for p in STATIC.glob("*.html")))
def test_no_external_subresource_in_any_page(page):
    html = (STATIC / page).read_text(encoding="utf-8")
    hits = re.findall(
        r"""(?:src|href)\s*=\s*["'](https?://[^"']+)["']""", html)
    # url(...) / @import in inline styles would also hit the wire:
    hits += re.findall(r"""url\(\s*['"]?(https?://[^)'"]+)""", html)
    hits += re.findall(r"""@import\s+['"]?(https?://[^;'"]+)""", html)
    bad = [h for h in hits
           if not any(h.startswith(p) for p in ALLOWED_EXTERNAL_HREF_PREFIXES)]
    assert not bad, f"{page} loads external resources: {bad}"
